config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  get 'pages/home'

  get 'pages/welcome'
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	 
	

  self.abstract_class = true

  validates_with SubmissionValidator

  
  #validates :Popcorn_Machine, uniqueness: {scope: :Event_Date, message: "is not available during your Event Date"}
end 

app/models/submission.rb
 
class Submission < ApplicationRecord

	 	
	#validates :Event_Date, inclusion: {in: %w(:Pick_up_Date :Event_Date :Drop_off_Date), message: "Event day does not fall within the Pick up and Drop off Date"}
	#validates :Pick_up_Date, inclusion: {in: %w(:Pick_up_Date :Event_Date), message: "Event day does not fall within the Pick up and Drop off Date"}
	validates :Popcorn_Machine, uniqueness: {scope: :Event_Date, message: "is not available during your Event Date"} , allow_blank: true 
	validates :Popcorn_Machine, uniqueness: {scope: :Pick_Up_Date, message: "is not available during your Pick Up Date"} , allow_blank: true 
	validates :Popcorn_Machine, uniqueness: {scope: :Drop_Off_Date, message: "is not available during your Drop off Date"} , allow_blank: true
	
end 

	

app/models/submission_validator.rb
 
 class SubmissionValidator < ActiveModel::Validator
	def validate(record)
		if record.Pick_Up_Date > record.Drop_Off_Date
			record.errors[:Pick_Up_Date] <<  "must be before Drop off Date"
		end 
		if record.Event_Date.between?(record.Pick_Up_Date, record.Drop_Off_Date)
		else
			record.errors[:Event_Date] << "must be between pick up and drop off date"
		end
		if record.Drop_Off_Date > record.Event_Date + 2
			record.errors[:Drop_Off_Date]  << "can not be more than two days after pick up date "
		end 

		


	end
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def welcome
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
        SubmissionMailer.submission_success(@submission).deliver_later

      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:First_Name, :Last_Name, :Email, :Phone_Number, :Event_Date, :Event_Time, :Event_Name, :Event_Description, :Pick_Up_Date, :Drop_Off_Date, :Popcorn_Machine, :SnowKone_Machine, :Chocolate_Fountain, :Cotton_Candy_Machine, :Margaritaville, :Pancake_Griddle_A, :Pancake_Griddle_B, :Pancake_Griddle_C, :Epson_Projector, :Projector_Screen, :Fender_Speakers_Blutooth, :Fender_Speakers_Wired, :microphone_and_Stand, :Cornhole, :Kan_Jam, :Bocce_Ball, :Washer_Toss, :White_Canopy_A, :White_Canopy_B, :White_Canopy_C, :Strobe_Lights, :Red_Police_Light, :Six_Light_Helicopter, :Black_Light, :Extention_Cord_A, :Extention_Cord_B, :Extention_cord_C, :Water_Cooler_A, :Water_Cooler_B, :Water_Cooler_C, :Ice_Chest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IRHASystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
  	<%= "__________________________________"%>
  	<img src = "/Copy of IRHA Logo-Transparent.png"style="width:256px;height:128px;">
  	<%= "__________________________________"%>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/submission_message.html.erb
Thank you for submitting your equipment request <%= submission.Name %>
===============================================

Thanks for joining and have a great day!

app/views/pages/home.html.erb
<h1>Inter-Residence Hall Association: Equipment Request Page</h1>

<p>
	<%= simple_format("Create a New Request \n 
	Check out our Equipment Catalog") %>
</p>
<p>
<%= link_to "New Form", 
{:controller => 'submissions', :action => 'new'}
%>
</p>

app/views/pages/welcome.html.erb
<h1>Pages#welcome</h1>
<p>Find me in app/views/pages/welcome.html.erb</p>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Submissions</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Event date</th>
      <th>Event time</th>
      <th>Event name</th>
      <th>Event description</th>
      <th>Pick up date</th>
      <th>Drop off date</th>
      <th>Popcorn machine</th>
      <th>Snowkone machine</th>
      <th>Chocolate fountain</th>
      <th>Cotton candy machine</th>
      <th>Margaritaville</th>
      <th>Pancake griddle a</th>
      <th>Pancake griddle b</th>
      <th>Pancake griddle c</th>
      <th>Epson projector</th>
      <th>Projector screen</th>
      <th>Fender speakers blutooth</th>
      <th>Fender speakers wired</th>
      <th>Microphone and stand</th>
      <th>Cornhole</th>
      <th>Kan jam</th>
      <th>Bocce ball</th>
      <th>Washer toss</th>
      <th>White canopy a</th>
      <th>White canopy b</th>
      <th>White canopy c</th>
      <th>Strobe lights</th>
      <th>Red police light</th>
      <th>Six light helicopter</th>
      <th>Black light</th>
      <th>Extention cord a</th>
      <th>Extention cord b</th>
      <th>Extention cord c</th>
      <th>Water cooler a</th>
      <th>Water cooler b</th>
      <th>Water cooler c</th>
      <th>Ice chest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.First_Name %></td>
        <td><%= submission.Last_Name %></td>
        <td><%= submission.Email %></td>
        <td><%= submission.Phone_Number %></td>
        <td><%= submission.Event_Date %></td>
        <td><%= submission.Event_Time %></td>
        <td><%= submission.Event_Name %></td>
        <td><%= submission.Event_Description %></td>
        <td><%= submission.Pick_Up_Date %></td>
        <td><%= submission.Drop_Off_Date %></td>
        <td><%= submission.Popcorn_Machine %></td>
        <td><%= submission.SnowKone_Machine %></td>
        <td><%= submission.Chocolate_Fountain %></td>
        <td><%= submission.Cotton_Candy_Machine %></td>
        <td><%= submission.Margaritaville %></td>
        <td><%= submission.Pancake_Griddle_A %></td>
        <td><%= submission.Pancake_Griddle_B %></td>
        <td><%= submission.Pancake_Griddle_C %></td>
        <td><%= submission.Epson_Projector %></td>
        <td><%= submission.Projector_Screen %></td>
        <td><%= submission.Fender_Speakers_Blutooth %></td>
        <td><%= submission.Fender_Speakers_Wired %></td>
        <td><%= submission.microphone_and_Stand %></td>
        <td><%= submission.Cornhole %></td>
        <td><%= submission.Kan_Jam %></td>
        <td><%= submission.Bocce_Ball %></td>
        <td><%= submission.Washer_Toss %></td>
        <td><%= submission.White_Canopy_A %></td>
        <td><%= submission.White_Canopy_B %></td>
        <td><%= submission.White_Canopy_C %></td>
        <td><%= submission.Strobe_Lights %></td>
        <td><%= submission.Red_Police_Light %></td>
        <td><%= submission.Six_Light_Helicopter %></td>
        <td><%= submission.Black_Light %></td>
        <td><%= submission.Extention_Cord_A %></td>
        <td><%= submission.Extention_Cord_B %></td>
        <td><%= submission.Extention_cord_C %></td>
        <td><%= submission.Water_Cooler_A %></td>
        <td><%= submission.Water_Cooler_B %></td>
        <td><%= submission.Water_Cooler_C %></td>
        <td><%= submission.Ice_Chest %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @submission.First_Name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @submission.Last_Name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @submission.Email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @submission.Phone_Number %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @submission.Event_Date %>
</p>

<p>
  <strong>Event time:</strong>
  <%= @submission.Event_Time %>
</p>

<p>
  <strong>Event name:</strong>
  <%= @submission.Event_Name %>
</p>

<p>
  <strong>Event description:</strong>
  <%= @submission.Event_Description %>
</p>

<p>
  <strong>Pick up date:</strong>
  <%= @submission.Pick_Up_Date %>
</p>

<p>
  <strong>Drop off date:</strong>
  <%= @submission.Drop_Off_Date %>
</p>

<p>
  <strong>Popcorn machine:</strong>
  <%= @submission.Popcorn_Machine %>
</p>

<p>
  <strong>Snowkone machine:</strong>
  <%= @submission.SnowKone_Machine %>
</p>

<p>
  <strong>Chocolate fountain:</strong>
  <%= @submission.Chocolate_Fountain %>
</p>

<p>
  <strong>Cotton candy machine:</strong>
  <%= @submission.Cotton_Candy_Machine %>
</p>

<p>
  <strong>Margaritaville:</strong>
  <%= @submission.Margaritaville %>
</p>

<p>
  <strong>Pancake griddle a:</strong>
  <%= @submission.Pancake_Griddle_A %>
</p>

<p>
  <strong>Pancake griddle b:</strong>
  <%= @submission.Pancake_Griddle_B %>
</p>

<p>
  <strong>Pancake griddle c:</strong>
  <%= @submission.Pancake_Griddle_C %>
</p>

<p>
  <strong>Epson projector:</strong>
  <%= @submission.Epson_Projector %>
</p>

<p>
  <strong>Projector screen:</strong>
  <%= @submission.Projector_Screen %>
</p>

<p>
  <strong>Fender speakers blutooth:</strong>
  <%= @submission.Fender_Speakers_Blutooth %>
</p>

<p>
  <strong>Fender speakers wired:</strong>
  <%= @submission.Fender_Speakers_Wired %>
</p>

<p>
  <strong>Microphone and stand:</strong>
  <%= @submission.microphone_and_Stand %>
</p>

<p>
  <strong>Cornhole:</strong>
  <%= @submission.Cornhole %>
</p>

<p>
  <strong>Kan jam:</strong>
  <%= @submission.Kan_Jam %>
</p>

<p>
  <strong>Bocce ball:</strong>
  <%= @submission.Bocce_Ball %>
</p>

<p>
  <strong>Washer toss:</strong>
  <%= @submission.Washer_Toss %>
</p>

<p>
  <strong>White canopy a:</strong>
  <%= @submission.White_Canopy_A %>
</p>

<p>
  <strong>White canopy b:</strong>
  <%= @submission.White_Canopy_B %>
</p>

<p>
  <strong>White canopy c:</strong>
  <%= @submission.White_Canopy_C %>
</p>

<p>
  <strong>Strobe lights:</strong>
  <%= @submission.Strobe_Lights %>
</p>

<p>
  <strong>Red police light:</strong>
  <%= @submission.Red_Police_Light %>
</p>

<p>
  <strong>Six light helicopter:</strong>
  <%= @submission.Six_Light_Helicopter %>
</p>

<p>
  <strong>Black light:</strong>
  <%= @submission.Black_Light %>
</p>

<p>
  <strong>Extention cord a:</strong>
  <%= @submission.Extention_Cord_A %>
</p>

<p>
  <strong>Extention cord b:</strong>
  <%= @submission.Extention_Cord_B %>
</p>

<p>
  <strong>Extention cord c:</strong>
  <%= @submission.Extention_cord_C %>
</p>

<p>
  <strong>Water cooler a:</strong>
  <%= @submission.Water_Cooler_A %>
</p>

<p>
  <strong>Water cooler b:</strong>
  <%= @submission.Water_Cooler_B %>
</p>

<p>
  <strong>Water cooler c:</strong>
  <%= @submission.Water_Cooler_C %>
</p>

<p>
  <strong>Ice chest:</strong>
  <%= @submission.Ice_Chest %>
</p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>